/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function clipboardInitialize(codeExts: Array<string>, imagExts: Array<string>, exceExts: Array<string>, reportFile: ((err: Error | null, arg: Array<FileInfo>) => any), reportShot: ((err: Error | null, arg: ShotInfo) => any), log: ((err: Error | null, arg: string) => any)): void

export interface FileInfo {
  name: string
  path: string
  fileType: FileType
  extension: string
  pname: string
  pid: number
}

export declare const enum FileType {
  IMAGE = 0,
  CODE = 1,
  EXCEL = 2
}

export interface ShotInfo {
  pname: string
  pid: number
  data: Uint8Array
}
